CREATE DATABASE cars;

CREATE TABLE cars (
	id INT,
	car_make VARCHAR(50),
	car_model VARCHAR(50),
	car_model_year INT
);
insert into cars (id, car_make, car_model, car_model_year) values (1, 'BMW', '7 Series', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (2, 'Volvo', 'C70', 2013);
insert into cars (id, car_make, car_model, car_model_year) values (3, 'Chevrolet', 'Suburban 1500', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (4, 'Honda', 'Pilot', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (5, 'Lamborghini', 'Gallardo', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (6, 'Volkswagen', 'GTI', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (7, 'Toyota', 'FJ Cruiser', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (8, 'Volvo', 'S60', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (9, 'Kia', 'Rio', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (10, 'BMW', '7 Series', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (11, 'MG', 'MGB', 1977);
insert into cars (id, car_make, car_model, car_model_year) values (12, 'Buick', 'Regal', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (13, 'Infiniti', 'G', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (14, 'Audi', 'Q7', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (15, 'Ford', 'Crown Victoria', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (16, 'GMC', 'Savana 3500', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (17, 'Mitsubishi', 'Eclipse', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (18, 'Mercury', 'Mariner', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (19, 'Pontiac', 'Grand Prix', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (20, 'Dodge', 'Ram Van 3500', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (21, 'Oldsmobile', 'Achieva', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (22, 'Ford', 'Escort', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (23, 'Lamborghini', 'Gallardo', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (24, 'Cadillac', 'XLR-V', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (25, 'Mercury', 'Sable', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (26, 'Chevrolet', 'Corvette', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (27, 'Mazda', 'RX-8', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (28, 'Chevrolet', 'Cobalt SS', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (29, 'Toyota', 'RAV4', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (30, 'Pontiac', 'Fiero', 1985);
insert into cars (id, car_make, car_model, car_model_year) values (31, 'Acura', 'RDX', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (32, 'Volkswagen', 'Jetta', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (33, 'Mitsubishi', 'Pajero', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (34, 'Ford', 'Econoline E250', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (35, 'Oldsmobile', 'Cutlass Supreme', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (36, 'Jaguar', 'XK Series', 2013);
insert into cars (id, car_make, car_model, car_model_year) values (37, 'Isuzu', 'i-Series', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (38, 'Hyundai', 'XG350', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (39, 'Chevrolet', 'Astro', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (40, 'Mercury', 'Mountaineer', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (41, 'Chevrolet', 'G-Series G30', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (42, 'Dodge', 'Ram Van 3500', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (43, 'Dodge', 'Ram 1500', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (44, 'Ford', 'Aspire', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (45, 'Mercedes-Benz', 'W201', 1984);
insert into cars (id, car_make, car_model, car_model_year) values (46, 'Jaguar', 'S-Type', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (47, 'Ford', 'Club Wagon', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (48, 'Chrysler', 'Sebring', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (49, 'Mazda', 'B-Series', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (50, 'Mitsubishi', 'Eclipse', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (51, 'Cadillac', 'Catera', 2000);
insert into cars (id, car_make, car_model, car_model_year) values (52, 'Chevrolet', 'Caprice', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (53, 'Porsche', '944', 1991);
insert into cars (id, car_make, car_model, car_model_year) values (54, 'Ford', 'Explorer', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (55, 'BMW', '3 Series', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (56, 'Ford', 'E-Series', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (57, 'BMW', 'Z4', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (58, 'Chevrolet', 'Tahoe', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (59, 'Chevrolet', 'Cavalier', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (60, 'GMC', '3500 Club Coupe', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (61, 'Toyota', 'Land Cruiser', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (62, 'Toyota', 'Sienna', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (63, 'Subaru', 'Legacy', 1991);
insert into cars (id, car_make, car_model, car_model_year) values (64, 'Chevrolet', 'Camaro', 1967);
insert into cars (id, car_make, car_model, car_model_year) values (65, 'Mercedes-Benz', 'E-Class', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (66, 'Mitsubishi', 'Expo', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (67, 'GMC', '2500 Club Coupe', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (68, 'Kia', 'Rio', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (69, 'Plymouth', 'Breeze', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (70, 'Toyota', 'Highlander', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (71, 'Ford', 'Econoline E250', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (72, 'Ford', 'F250', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (73, 'Chrysler', 'New Yorker', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (74, 'Plymouth', 'Prowler', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (75, 'Toyota', 'Supra', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (76, 'Mercedes-Benz', 'C-Class', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (77, 'GMC', 'Rally Wagon 1500', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (78, 'Subaru', 'Tribeca', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (79, 'Mercury', 'Villager', 2000);
insert into cars (id, car_make, car_model, car_model_year) values (80, 'Audi', 'RS4', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (81, 'Suzuki', 'Esteem', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (82, 'Dodge', 'Ram', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (83, 'Mitsubishi', 'RVR', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (84, 'Infiniti', 'J', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (85, 'Land Rover', 'Freelander', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (86, 'Toyota', '4Runner', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (87, 'Audi', 'A4', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (88, 'Ford', 'GT500', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (89, 'Ford', 'E250', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (90, 'Suzuki', 'Reno', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (91, 'Isuzu', 'Stylus', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (92, 'BMW', '530', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (93, 'Audi', 'S5', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (94, 'Volkswagen', 'Eurovan', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (95, 'Porsche', 'Boxster', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (96, 'Mazda', 'Millenia', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (97, 'Ford', 'Ranger', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (98, 'Chevrolet', 'Express 1500', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (99, 'Aston Martin', 'DB9', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (100, 'Chrysler', 'Town & Country', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (101, 'Dodge', 'Grand Caravan', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (102, 'BMW', 'M6', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (103, 'Daihatsu', 'Rocky', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (104, 'Land Rover', 'LR4', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (105, 'Volvo', 'V70', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (106, 'Kia', 'Rondo', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (107, 'Suzuki', 'Grand Vitara', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (108, 'Honda', 'Pilot', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (109, 'Mitsubishi', 'Montero', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (110, 'Ford', 'Bronco II', 1987);
insert into cars (id, car_make, car_model, car_model_year) values (111, 'Mazda', 'RX-7', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (112, 'Pontiac', '1000', 1984);
insert into cars (id, car_make, car_model, car_model_year) values (113, 'BMW', 'M3', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (114, 'Lincoln', 'MKT', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (115, 'Toyota', 'Truck Xtracab SR5', 1989);
insert into cars (id, car_make, car_model, car_model_year) values (116, 'Nissan', 'Murano', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (117, 'Aston Martin', 'DBS', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (118, 'Dodge', 'Ram Van B350', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (119, 'GMC', 'Vandura 2500', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (120, 'Scion', 'xB', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (121, 'Aston Martin', 'V8 Vantage', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (122, 'Volkswagen', 'Touareg', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (123, 'Dodge', 'Durango', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (124, 'Infiniti', 'QX56', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (125, 'Mitsubishi', 'Mirage', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (126, 'Mercury', 'Mountaineer', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (127, 'Mercedes-Benz', 'SL-Class', 1987);
insert into cars (id, car_make, car_model, car_model_year) values (128, 'Honda', 'Accord', 1985);
insert into cars (id, car_make, car_model, car_model_year) values (129, 'Honda', 'Prelude', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (130, 'Chevrolet', 'Suburban', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (131, 'Ford', 'LTD Crown Victoria', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (132, 'Nissan', 'Pathfinder', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (133, 'Lincoln', 'MKX', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (134, 'Honda', 'CR-V', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (135, 'GMC', 'Rally Wagon 1500', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (136, 'Chevrolet', 'Monte Carlo', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (137, 'Volvo', 'S70', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (138, 'Hyundai', 'Sonata', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (139, 'Mazda', 'Tribute', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (140, 'Chevrolet', 'Astro', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (141, 'Mitsubishi', 'Eclipse', 2000);
insert into cars (id, car_make, car_model, car_model_year) values (142, 'Mitsubishi', 'Chariot', 1988);
insert into cars (id, car_make, car_model, car_model_year) values (143, 'Honda', 'Insight', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (144, 'Lincoln', 'Continental Mark VII', 1989);
insert into cars (id, car_make, car_model, car_model_year) values (145, 'Nissan', 'Frontier', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (146, 'GMC', 'Sierra 3500', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (147, 'Toyota', 'Echo', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (148, 'Mazda', '323', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (149, 'Chrysler', 'Fifth Ave', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (150, 'Chevrolet', 'Express', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (151, 'GMC', '3500 Club Coupe', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (152, 'Ford', 'Bronco', 1987);
insert into cars (id, car_make, car_model, car_model_year) values (153, 'Volkswagen', 'Passat', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (154, 'Volkswagen', 'Passat', 1985);
insert into cars (id, car_make, car_model, car_model_year) values (155, 'BMW', 'X6', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (156, 'Buick', 'Coachbuilder', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (157, 'Nissan', 'Sentra', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (158, 'Subaru', 'Forester', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (159, 'Plymouth', 'Neon', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (160, 'Chevrolet', 'Silverado 1500', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (161, 'BMW', 'Z8', 2000);
insert into cars (id, car_make, car_model, car_model_year) values (162, 'Toyota', '4Runner', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (163, 'Isuzu', 'Trooper', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (164, 'Mercedes-Benz', 'CLS-Class', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (165, 'Mercury', 'Sable', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (166, 'Daewoo', 'Lanos', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (167, 'GMC', 'Savana 2500', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (168, 'Volkswagen', 'Eurovan', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (169, 'Mazda', 'B-Series Plus', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (170, 'Cadillac', 'Catera', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (171, 'Infiniti', 'I', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (172, 'Oldsmobile', 'Bravada', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (173, 'Ford', 'Edge', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (174, 'Audi', 'R8', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (175, 'Mazda', 'Mazda3', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (176, 'Ford', 'LTD Crown Victoria', 1988);
insert into cars (id, car_make, car_model, car_model_year) values (177, 'Volkswagen', 'Touareg', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (178, 'Mercury', 'Monterey', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (179, 'Mercedes-Benz', 'E-Class', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (180, 'Plymouth', 'Roadrunner', 1969);
insert into cars (id, car_make, car_model, car_model_year) values (181, 'Isuzu', 'i-290', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (182, 'Pontiac', '6000', 1990);
insert into cars (id, car_make, car_model, car_model_year) values (183, 'Pontiac', 'Grand Prix', 1989);
insert into cars (id, car_make, car_model, car_model_year) values (184, 'MINI', 'Cooper', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (185, 'Mercedes-Benz', 'CLS-Class', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (186, 'Mitsubishi', 'i-MiEV', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (187, 'Maserati', 'Spyder', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (188, 'BMW', '7 Series', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (189, 'GMC', 'Safari', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (190, 'Lexus', 'IS', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (191, 'Buick', 'Terraza', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (192, 'Mitsubishi', 'Lancer', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (193, 'BMW', '3 Series', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (194, 'Ford', 'F350', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (195, 'Land Rover', 'Freelander', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (196, 'Mercury', 'Marquis', 1985);
insert into cars (id, car_make, car_model, car_model_year) values (197, 'Aston Martin', 'DB9', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (198, 'Lotus', 'Elise', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (199, 'Nissan', 'GT-R', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (200, 'Mitsubishi', 'Lancer', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (201, 'Dodge', 'Nitro', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (202, 'Mitsubishi', 'Chariot', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (203, 'Acura', 'Legend', 1988);
insert into cars (id, car_make, car_model, car_model_year) values (204, 'Honda', 'Pilot', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (205, 'Hyundai', 'Elantra', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (206, 'Hyundai', 'Tucson', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (207, 'Oldsmobile', 'Intrigue', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (208, 'Ford', 'Flex', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (209, 'Honda', 'Insight', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (210, 'Mercedes-Benz', 'CLS-Class', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (211, 'Ford', 'F350', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (212, 'Oldsmobile', 'Toronado', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (213, 'Nissan', 'Rogue', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (214, 'Aston Martin', 'DB9', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (215, 'Lotus', 'Esprit Turbo', 1984);
insert into cars (id, car_make, car_model, car_model_year) values (216, 'Chevrolet', 'Express 2500', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (217, 'Mazda', 'Mazda6', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (218, 'Nissan', 'Maxima', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (219, 'Toyota', 'Matrix', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (220, 'Chevrolet', 'Suburban 2500', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (221, 'Hyundai', 'Sonata', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (222, 'Audi', 'Q7', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (223, 'Mercedes-Benz', 'SLK-Class', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (224, 'Chevrolet', 'Corvette', 1958);
insert into cars (id, car_make, car_model, car_model_year) values (225, 'Infiniti', 'Q', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (226, 'Mercury', 'Sable', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (227, 'Mitsubishi', 'Lancer', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (228, 'Honda', 'CR-V', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (229, 'Porsche', '928', 1988);
insert into cars (id, car_make, car_model, car_model_year) values (230, 'Land Rover', 'Defender', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (231, 'Lexus', 'SC', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (232, 'Lexus', 'IS', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (233, 'Lamborghini', 'Murciélago', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (234, 'Audi', 'A4', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (235, 'Audi', 'A4', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (236, 'GMC', 'Sierra 1500', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (237, 'Chevrolet', 'Tahoe', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (238, 'Daewoo', 'Nubira', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (239, 'Mitsubishi', 'Truck', 1988);
insert into cars (id, car_make, car_model, car_model_year) values (240, 'Dodge', 'Dakota', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (241, 'Cadillac', 'STS', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (242, 'Toyota', 'Land Cruiser', 2013);
insert into cars (id, car_make, car_model, car_model_year) values (243, 'BMW', '325', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (244, 'Lexus', 'ES', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (245, 'Volkswagen', 'GTI', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (246, 'Volkswagen', 'Golf', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (247, 'Audi', 'A3', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (248, 'Lincoln', 'MKZ', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (249, 'Acura', 'Legend', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (250, 'Pontiac', 'Vibe', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (251, 'Oldsmobile', 'Cutlass', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (252, 'Mercury', 'Sable', 1986);
insert into cars (id, car_make, car_model, car_model_year) values (253, 'Jaguar', 'XJ Series', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (254, 'Dodge', 'Viper', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (255, 'Isuzu', 'Impulse', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (256, 'Lexus', 'SC', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (257, 'Ford', 'Probe', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (258, 'Mercedes-Benz', '300E', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (259, 'Hyundai', 'Santa Fe', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (260, 'Lincoln', 'Continental', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (261, 'Mercedes-Benz', 'E-Class', 1986);
insert into cars (id, car_make, car_model, car_model_year) values (262, 'Subaru', 'Tribeca', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (263, 'Mazda', 'MX-5', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (264, 'Buick', 'Somerset', 1985);
insert into cars (id, car_make, car_model, car_model_year) values (265, 'Ford', 'Fairlane', 1966);
insert into cars (id, car_make, car_model, car_model_year) values (266, 'Subaru', 'Forester', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (267, 'Chevrolet', 'Cruze', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (268, 'Volkswagen', 'Golf', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (269, 'Acura', 'TSX', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (270, 'Mercedes-Benz', 'Sprinter 3500', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (271, 'GMC', 'Yukon XL 1500', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (272, 'Dodge', 'Ram Van 3500', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (273, 'Subaru', 'Legacy', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (274, 'Ford', 'Probe', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (275, 'Mercury', 'Grand Marquis', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (276, 'Ford', 'Bronco', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (277, 'Jeep', 'Patriot', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (278, 'Toyota', 'Celica', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (279, 'Infiniti', 'I', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (280, 'GMC', 'Canyon', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (281, 'Acura', 'TSX', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (282, 'Smart', 'Fortwo', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (283, 'Toyota', 'Solara', 2000);
insert into cars (id, car_make, car_model, car_model_year) values (284, 'Chevrolet', 'Suburban 1500', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (285, 'Audi', 'RS 4', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (286, 'Isuzu', 'Amigo', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (287, 'MINI', 'Cooper Countryman', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (288, 'BMW', 'X6 M', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (289, 'Suzuki', 'Verona', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (290, 'Volkswagen', 'Phaeton', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (291, 'Mazda', 'Protege', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (292, 'Lincoln', 'Navigator', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (293, 'Pontiac', 'Bonneville', 1991);
insert into cars (id, car_make, car_model, car_model_year) values (294, 'Volvo', 'V70', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (295, 'Cadillac', 'Escalade', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (296, 'Land Rover', 'Range Rover', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (297, 'Mazda', 'MX-5', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (298, 'BMW', 'X5', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (299, 'Kia', 'Optima', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (300, 'Pontiac', 'Torrent', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (301, 'Lincoln', 'Continental', 1989);
insert into cars (id, car_make, car_model, car_model_year) values (302, 'GMC', 'Suburban 2500', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (303, 'Toyota', '4Runner', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (304, 'Mitsubishi', 'Space', 1984);
insert into cars (id, car_make, car_model, car_model_year) values (305, 'Toyota', 'Celica', 2000);
insert into cars (id, car_make, car_model, car_model_year) values (306, 'Dodge', 'Challenger', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (307, 'Suzuki', 'Equator', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (308, 'Chevrolet', 'Express 3500', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (309, 'Eagle', 'Summit', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (310, 'Mazda', 'MX-5', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (311, 'Volkswagen', 'Rabbit', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (312, 'Acura', 'TL', 2000);
insert into cars (id, car_make, car_model, car_model_year) values (313, 'Subaru', 'Forester', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (314, 'Infiniti', 'M', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (315, 'Ford', 'Fusion', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (316, 'Porsche', '928', 1986);
insert into cars (id, car_make, car_model, car_model_year) values (317, 'Chevrolet', 'Silverado 2500', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (318, 'Lotus', 'Esprit', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (319, 'Lincoln', 'Town Car', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (320, 'Dodge', 'Stealth', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (321, 'BMW', '6 Series', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (322, 'Dodge', 'Grand Caravan', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (323, 'Audi', 'A3', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (324, 'Mazda', 'Mazdaspeed6', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (325, 'GMC', 'Suburban 2500', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (326, 'Mercedes-Benz', 'CLK-Class', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (327, 'Lexus', 'IS', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (328, 'Dodge', 'Avenger', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (329, 'Chevrolet', 'Corvette', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (330, 'Suzuki', 'XL-7', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (331, 'Toyota', 'Cressida', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (332, 'Toyota', 'Solara', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (333, 'Ford', 'Th!nk', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (334, 'Porsche', 'Boxster', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (335, 'Buick', 'Century', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (336, 'Lexus', 'ES', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (337, 'Mercury', 'Grand Marquis', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (338, 'Subaru', 'Legacy', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (339, 'Buick', 'LaCrosse', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (340, 'Cadillac', 'CTS', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (341, 'Toyota', 'Prius', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (342, 'Mitsubishi', 'Sigma', 1989);
insert into cars (id, car_make, car_model, car_model_year) values (343, 'Mercedes-Benz', 'CLS-Class', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (344, 'Hummer', 'H2', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (345, 'Pontiac', 'Bonneville', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (346, 'Volkswagen', 'Passat', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (347, 'Infiniti', 'QX', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (348, 'Infiniti', 'Q', 2000);
insert into cars (id, car_make, car_model, car_model_year) values (349, 'Saturn', 'Outlook', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (350, 'BMW', '3 Series', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (351, 'Toyota', 'RAV4', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (352, 'Dodge', 'Dakota', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (353, 'Mercury', 'Capri', 1986);
insert into cars (id, car_make, car_model, car_model_year) values (354, 'Saab', '9-3', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (355, 'Volkswagen', 'GTI', 1989);
insert into cars (id, car_make, car_model, car_model_year) values (356, 'Mercury', 'Marquis', 1986);
insert into cars (id, car_make, car_model, car_model_year) values (357, 'Hyundai', 'Sonata', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (358, 'Honda', 'Accord', 1991);
insert into cars (id, car_make, car_model, car_model_year) values (359, 'Dodge', 'Ram', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (360, 'Maserati', 'GranTurismo', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (361, 'Hyundai', 'Azera', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (362, 'Lincoln', 'LS', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (363, 'Suzuki', 'X-90', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (364, 'Volkswagen', 'Golf', 1986);
insert into cars (id, car_make, car_model, car_model_year) values (365, 'Toyota', 'Sequoia', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (366, 'Cadillac', 'Seville', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (367, 'Toyota', 'Avalon', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (368, 'Lincoln', 'Continental Mark VII', 1987);
insert into cars (id, car_make, car_model, car_model_year) values (369, 'Maserati', 'Spyder', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (370, 'Toyota', 'Prius', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (371, 'Toyota', 'Avalon', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (372, 'Plymouth', 'Roadrunner', 1969);
insert into cars (id, car_make, car_model, car_model_year) values (373, 'Ford', 'Econoline E350', 2000);
insert into cars (id, car_make, car_model, car_model_year) values (374, 'Maserati', 'Karif', 1990);
insert into cars (id, car_make, car_model, car_model_year) values (375, 'Dodge', 'Caravan', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (376, 'Volkswagen', 'Passat', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (377, 'GMC', 'Sierra', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (378, 'Infiniti', 'M', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (379, 'Lincoln', 'Town Car', 1986);
insert into cars (id, car_make, car_model, car_model_year) values (380, 'Ford', 'Edge', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (381, 'Volvo', 'C70', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (382, 'Toyota', 'MR2', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (383, 'Lotus', 'Elise', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (384, 'Land Rover', 'Range Rover', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (385, 'Toyota', '4Runner', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (386, 'Honda', 'Civic', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (387, 'Mitsubishi', 'GTO', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (388, 'Audi', 'A3', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (389, 'Honda', 'Insight', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (390, 'Suzuki', 'Samurai', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (391, 'Ford', 'Mustang', 1987);
insert into cars (id, car_make, car_model, car_model_year) values (392, 'Chevrolet', 'Silverado 1500', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (393, 'Kia', 'Sorento', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (394, 'Dodge', 'Viper', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (395, 'Mercury', 'Mystique', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (396, 'Cadillac', 'Catera', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (397, 'Infiniti', 'Q', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (398, 'Dodge', 'Caravan', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (399, 'Dodge', 'Ram Van B350', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (400, 'Ford', 'Courier', 1986);
insert into cars (id, car_make, car_model, car_model_year) values (401, 'Cadillac', 'CTS-V', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (402, 'Toyota', 'Prius', 2001);
insert into cars (id, car_make, car_model, car_model_year) values (403, 'Subaru', 'Impreza', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (404, 'Chevrolet', '3500', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (405, 'Honda', 'Odyssey', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (406, 'Hyundai', 'Tiburon', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (407, 'Lamborghini', 'Gallardo', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (408, 'Lincoln', 'LS', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (409, 'GMC', 'Safari', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (410, 'Porsche', '911', 1986);
insert into cars (id, car_make, car_model, car_model_year) values (411, 'GMC', 'Safari', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (412, 'Dodge', 'Avenger', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (413, 'Land Rover', 'Range Rover', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (414, 'GMC', 'Savana', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (415, 'Chevrolet', 'Sportvan G30', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (416, 'Jeep', 'Cherokee', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (417, 'Aston Martin', 'Vantage', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (418, 'Kia', 'Amanti', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (419, 'Infiniti', 'M', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (420, 'Chrysler', '300M', 2000);
insert into cars (id, car_make, car_model, car_model_year) values (421, 'Chrysler', 'Aspen', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (422, 'Plymouth', 'Voyager', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (423, 'Chevrolet', 'Caprice', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (424, 'Toyota', 'Highlander', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (425, 'Audi', 'Cabriolet', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (426, 'Cadillac', 'Fleetwood', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (427, 'Mazda', 'RX-7', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (428, 'Chevrolet', 'S10', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (429, 'Mitsubishi', 'Precis', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (430, 'Chevrolet', 'Avalanche 1500', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (431, 'Chrysler', 'Pacifica', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (432, 'BMW', '530', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (433, 'Ford', 'Festiva', 1991);
insert into cars (id, car_make, car_model, car_model_year) values (434, 'Lamborghini', 'Countach', 1988);
insert into cars (id, car_make, car_model, car_model_year) values (435, 'Hyundai', 'Elantra', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (436, 'Pontiac', 'Firefly', 1991);
insert into cars (id, car_make, car_model, car_model_year) values (437, 'Mercedes-Benz', '500SL', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (438, 'Mitsubishi', 'Truck', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (439, 'GMC', 'Canyon', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (440, 'Chevrolet', 'Avalanche', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (441, 'BMW', 'M', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (442, 'Acura', 'MDX', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (443, 'Bentley', 'Continental GT', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (444, 'Mitsubishi', 'Mighty Max', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (445, 'GMC', 'Yukon XL 2500', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (446, 'Ford', 'Econoline E350', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (447, 'Isuzu', 'Rodeo', 1999);
insert into cars (id, car_make, car_model, car_model_year) values (448, 'Hyundai', 'Tucson', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (449, 'Maybach', 'Landaulet', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (450, 'Mitsubishi', 'Galant', 1984);
insert into cars (id, car_make, car_model, car_model_year) values (451, 'Lotus', 'Elan', 1992);
insert into cars (id, car_make, car_model, car_model_year) values (452, 'Audi', 'S4', 2009);
insert into cars (id, car_make, car_model, car_model_year) values (453, 'GMC', 'Sierra 2500', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (454, 'GMC', '2500', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (455, 'Ford', 'E-Series', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (456, 'BMW', '3 Series', 2011);
insert into cars (id, car_make, car_model, car_model_year) values (457, 'Audi', '80', 1990);
insert into cars (id, car_make, car_model, car_model_year) values (458, 'Honda', 'CR-X', 1984);
insert into cars (id, car_make, car_model, car_model_year) values (459, 'Pontiac', 'Parisienne', 1986);
insert into cars (id, car_make, car_model, car_model_year) values (460, 'Mitsubishi', 'Diamante', 2005);
insert into cars (id, car_make, car_model, car_model_year) values (461, 'BMW', 'Z4', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (462, 'BMW', '3 Series', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (463, 'Alfa Romeo', '164', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (464, 'Kia', 'Amanti', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (465, 'Lexus', 'IS-F', 2008);
insert into cars (id, car_make, car_model, car_model_year) values (466, 'Toyota', 'Matrix', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (467, 'Chevrolet', 'Silverado', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (468, 'GMC', 'Yukon XL 1500', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (469, 'Acura', 'NSX', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (470, 'Oldsmobile', 'Silhouette', 2003);
insert into cars (id, car_make, car_model, car_model_year) values (471, 'Mazda', 'MX-5', 2000);
insert into cars (id, car_make, car_model, car_model_year) values (472, 'Dodge', 'Ram 2500', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (473, 'Dodge', 'Charger', 1968);
insert into cars (id, car_make, car_model, car_model_year) values (474, 'Scion', 'tC', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (475, 'Suzuki', 'Forenza', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (476, 'Hyundai', 'Accent', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (477, 'Chevrolet', 'Suburban 2500', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (478, 'Chevrolet', 'Tahoe', 1998);
insert into cars (id, car_make, car_model, car_model_year) values (479, 'Subaru', 'Outback', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (480, 'Pontiac', 'Vibe', 2010);
insert into cars (id, car_make, car_model, car_model_year) values (481, 'Lincoln', 'Town Car', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (482, 'Ford', 'F250', 1995);
insert into cars (id, car_make, car_model, car_model_year) values (483, 'Lexus', 'RX Hybrid', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (484, 'Ford', 'GT', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (485, 'Jeep', 'Wrangler', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (486, 'Chevrolet', 'Express 1500', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (487, 'Cadillac', 'SRX', 2007);
insert into cars (id, car_make, car_model, car_model_year) values (488, 'Buick', 'Roadmaster', 1996);
insert into cars (id, car_make, car_model, car_model_year) values (489, 'Volkswagen', 'Type 2', 1986);
insert into cars (id, car_make, car_model, car_model_year) values (490, 'Dodge', 'D150', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (491, 'Ford', 'Taurus', 1997);
insert into cars (id, car_make, car_model, car_model_year) values (492, 'Volkswagen', 'Passat', 2002);
insert into cars (id, car_make, car_model, car_model_year) values (493, 'Plymouth', 'Laser', 1994);
insert into cars (id, car_make, car_model, car_model_year) values (494, 'Dodge', 'Dakota Club', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (495, 'Isuzu', 'Amigo', 1993);
insert into cars (id, car_make, car_model, car_model_year) values (496, 'Kia', 'Spectra', 2006);
insert into cars (id, car_make, car_model, car_model_year) values (497, 'Honda', 'Odyssey', 2004);
insert into cars (id, car_make, car_model, car_model_year) values (498, 'Ford', 'Mustang', 1984);
insert into cars (id, car_make, car_model, car_model_year) values (499, 'Honda', 'Ridgeline', 2012);
insert into cars (id, car_make, car_model, car_model_year) values (500, 'Oldsmobile', 'Bravada', 1992);
